package migrations

import (
	"bitbucket.org/infinity-exchange/mev-boost-relay/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration012CreateGetPayload = &migrate.Migration{
	Id: "012-create-get-payload",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableGetPayload + ` (
			id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,

			slot            bigint NOT NULL,

			slot_start_timestamp   bigint NOT NULL,
			request_timestamp bigint NOT NULL,
			decode_timestamp  bigint NOT NULL,

			proposer_pubkey varchar(98) NOT NULL,
			block_hash      varchar(66) NOT NULL,
			ms_into_slot    bigint NOT NULL
		);

		CREATE UNIQUE INDEX IF NOT EXISTS ` + vars.TableGetPayload + `_slot_pk_hash_idx ON ` + vars.TableGetPayload + `(slot, proposer_pubkey, block_hash);
	`},
	Down: []string{},

	DisableTransactionUp:   true,
	DisableTransactionDown: true,
}
