package migrations

import (
	"bitbucket.org/infinity-exchange/mev-boost-relay/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration015CreateBlockPublish = &migrate.Migration{
	Id: "015-create-block-publish",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableBlockPublish + ` (
			id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,
			slot            bigint NOT NULL,
			beacon_ip varchar(250) NOT NULL,
			slot_start_timestamp   bigint NOT NULL,
			publish_timestamp bigint NOT NULL,
			finish_timestamp  bigint NOT NULL,

			block_hash      varchar(66) NOT NULL,
			ms_into_slot    bigint NOT NULL,
			locate 			varchar(50)
		);

		CREATE UNIQUE INDEX IF NOT EXISTS ` + vars.TableBlockPublish + `_slot_pk_hash_idx ON ` + vars.TableBlockPublish + `(slot, block_hash, locate, beacon_ip);
	`},
	Down: []string{},

	DisableTransactionUp:   true,
	DisableTransactionDown: true,
}
